[default.probe]
# Use ST-Link or other compatible probe
protocol = "Swd"
speed = 4000

[default.flashing]
enabled = true
halt_afterwards = false

[default.reset]
enabled = true
halt_afterwards = false

[default.general]
chip = "STM32H743ZITx"

[default.rtt]
enabled = true
up_mode = "NoBlockTrim"
# Uncomment to use a specific RTT control block address
# control_block_address = 0x20000000
