[package]
name = "oxidrone-hal"
version = "0.1.0"
edition = "2024"

[dependencies]
heapless.workspace = true
nalgebra.workspace = true
embedded-hal.workspace = true
rtic-time.workspace = true
usb-device.workspace = true
