[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Use probe-rs for flashing and debugging
runner = "probe-rs run --chip STM32H743ZITx"

[build]
# Target for STM32H7 (Cortex-M7)
target = "thumbv7em-none-eabihf"

# Alternative runners (uncomment the one you prefer):
# For OpenOCD:
# runner = "arm-none-eabi-gdb -x openocd.gdb"

# For ST-Link:
# runner = "st-flash --format ihex write target/thumbv7em-none-eabihf/release/oxidrone.hex"
