name: Build Matek H743 Wing

on:
  push:
    paths: [ 'boards/matekh743/**' ]
  pull_request:
    paths: [ 'boards/matekh743/**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust and target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf

      - uses: extractions/setup-just@v3

      - name: Build Matek firmware
        run: just matekh743-release

      - name: Upload compiled firmware
        uses: actions/upload-artifact@v4
        with:
          name: matekh743
          path: target/thumbv7em-none-eabihf/release/matekh743

